### ISSUE TITLE
ASSISTANCE tab link  - bug

### ISSUE THREAD

**Issue by glucat** [Glucosio/glucosio-android#104]
when i was click on ASSISTANT tab from OVERVIEW tab it wasn't displaying anything, but when i was click it from HISTORY tab it was displays options.

Debug info:
 OS Version: 3.4.0(eng.user.20140509.125022)
 OS API Level: 18
 Device: C1904
 Model (and Product): C1904 (C1904)
 RELEASE: 4.3
 BRAND: Sony
 DISPLAY: 15.4.A.1.9
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 Build ID: 15.4.A.1.9
 MANUFACTURER: Sony
 SERIAL: YT910BF4RD
 USER: user
 HOST: su-buildpc-02

Extra Info: Nothing to show.

**Comment by bkerensa** [comment]
Can you triage this if its invalid we can close it

**Comment by piotrek1543** [comment]
Tested. No such strange bug has been found. 
You can close it :+1:
