### ISSUE TITLE
Add Advance Entry Types to Entry Dialog

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#109]
We should expand the Glucose entry dialog to be a multi metric/event entry dialog:

* [ ] Meal Data: Carbs, Proteins, Fats, Calories 
* [ ] Reminder:  User can set a reminder None is default but options for 15min, 30min, 1hr, 1 1/2 hr, 2 hr, 2 1/2 hr , 3 hr, 3 1/2 hr, 4 hr, 4 1/2 hr, 5hr
* [ ] Insulin Dose: User can indicate add a entry for when they inject insulin and which type of insulin they used and how man U
* [ ] Pill: User can indicate they took a pill diabetes medicine and type
* [ ] Notes: User can add any notes they would like perhaps up to 300 words
* [ ] Weight: User can log weight
* [ ] HbA1c: User can log a hba1c reading
* [ ] Cholesterol: User can log a cholesterol lab result
* [ ] Ketones: User can log ketones
* [ ] BP: User can log  BP (Systolic, Diastolic and Pulse)
* [ ] Physical Activity: User presented pull down with dozens of activity types and also able to add a comment to note info about the activity like how long etc and also a duration field

Feedback from /r/diabetes

**Comment by bkerensa** [comment]
This is how DM does this in their multi entry tool so user can add any of these entries without a glucose or with it. This lets the user see how all these factors impact their disease.

![screenshot_20151026-001114](https://cloud.githubusercontent.com/assets/859175/10723378/8a4743a2-7b77-11e5-96fd-1b52efeb1e5b.png)
![screenshot_20151026-001103](https://cloud.githubusercontent.com/assets/859175/10723375/8a449102-7b77-11e5-9ac5-92270cd241ad.png)
![screenshot_20151026-001058](https://cloud.githubusercontent.com/assets/859175/10723377/8a465c94-7b77-11e5-8230-bb407c663478.png)
![screenshot_20151026-001040](https://cloud.githubusercontent.com/assets/859175/10723379/8a47d89e-7b77-11e5-8dca-3369ddf3b341.png)
![screenshot_20151026-001023](https://cloud.githubusercontent.com/assets/859175/10723376/8a465172-7b77-11e5-96ba-34a9b92c054b.png)

**Comment by PaoloRotolo** [comment]
Ok, we need mockups from design team to find out how to register those information in Add Dialog and also where to display them in history.

**Comment by bkerensa** [comment]
OK looks like Satya said he won't be available till Nov 1. Can Chris's UX guy help?

**Comment by bkerensa** [comment]
@satya164 will need UX work for this and #134 and #98 these are pretty priority for our next release if you can work on this at your next availability that would be great

**Comment by bkerensa** [comment]
@satya164 Do you need any other info to work on this?

**Comment by bkerensa** [comment]
@satya164 Any chance you could take this on in the next week?

**Comment by satya164** [comment]
@bkerensa I'll work on it this weekend

**Comment by satya164** [comment]
Ok, so this is getting really complex here. Let's try to make it simpler. First lets clear up few things. I have no idea about these things, so please correct me where I'm wrong,

### What's the purpose of the Add Entry dialog?
As far as I understand, the current add entry dialog is used to add an entry for blood Glucose level. So, how do the following fit into it?

1. Cholestorol lab result
2. Blood pressure
3. Weight
4, Ketones
5. HbA1c reading

Is it frequent that users take a these tests at the same time as Glucose test? If yes, how frequent is it? If no, what's the frequency?

If these items aren't very frequent and don't coincide with the glucose tests, probably we need difefferent entry dialogs for these.

### Categorization of Glucose entry
So, the current Add entry dialog only supports entering the result after a meal. Looking at the list, I think it falls into following categories,

1. After meal (fields - type (e.g.- breakfast), meal data)
2. After injecting insulin (fields - type, amount)
3. After taking a pill (fields - type)
4. After a physical activity (fields - type, duration)

The idea is to categorize the entry, so that the user sees only the relevant input fields.

### Fields relevant to any category
1. Reminders - The UI will depend on how frequently people do a specific thing, e.g. - several times a day, once a day, once a week etc. The default value has to be optimized for the category.
2. Notes - May be should also allow to take a photo? Say, a prescription

cc @bkerensa

**Comment by bkerensa** [comment]
@satya164  1, 4 and 5 vary depending on the patient but I would say at least once a quarter to monthly depending on how often their doctor checks these. Although 5 (HBa1c) some people do check this daily as they now have home meters.

2 (BP) some people do this once or twice a day if they have hypertension alongside their diabetes which is common.

3. Many check their weight daily 

4. Many also check ketones regularly because this shows whether diabetes meds are casing ketoacidosis but also many have a LCHF diet which causes ketosis to burn fat instead of carbs for body fuel so people on this diet which is very common in diabetes would be checking ketones roughly once a week.

If you have a chance I would check out Diabetes:M and MySugr to see how they have a entry dialog for this. Diabetes:M lets you enter everything from one dialog and also setup reminders and add notes right in the one dialog. Hmm I dont know if a photo would be as useful to be honest.

**Comment by bkerensa** [comment]
@PaoloRotolo FYI as we add these metrics in once we get the UX we will want to then start thinking about syncing with Google Fit and other apps like MyFitnessPal as we can also automatically snag these metrics from those apps but also we can push these metrics to those apps to so they can use either and keep all their data in sync.

**Comment by satya164** [comment]
@bkerensa Yeah, but do the tests coincide with blood sugar tests? Does it make sense for these readings in the same dialog as the blood sugar entry dialog?

**Comment by bkerensa** [comment]
@satya164 Well I suppose having them all in one dialog would make it easier and less cluttered than having a dozen dialogs tucked elsewhere. And ultimately I think we hope to graph this data alongside glucose levels so people have a high resolution view of how these metrics impact their glucose and diabetes.

**Comment by satya164** [comment]
@bkerensa I think having all these in one dialog make it cluttered and make it harder to focus on the actual data the user wants to add.

About dozen dialogs tucked elsewhere, ultimately this will depend on the design, I'm sure we can find a good balance here.

About showing the data alongside glucose levels, we can always do that based on the timestamp of the entry.

**Comment by satya164** [comment]
When I look at the apps which throw every possible entry all in one dialog, I feel overwhelmed and confused on what are optional, what are required, what should I enter, what I don't.

I believe that entering data is a very crucial part of the app and it should be as easy and smooth as possible. And that's what will make Glucosio stand apart from other similar apps.

**Comment by bkerensa** [comment]
Okie dokie :) well we will wait for your proposed mockups

**Comment by satya164** [comment]
Here are some initial ideas,

![1 1-glucosio-add-types](https://cloud.githubusercontent.com/assets/1174278/11554066/b7be7bfa-99ba-11e5-9662-73bda1587851.png)

![2-glucosio-add](https://cloud.githubusercontent.com/assets/1174278/11554068/bd90d0f0-99ba-11e5-90e8-a77d7fc1e5ec.png)

**Comment by satya164** [comment]
We can ask for the meal data after the reading is added in a Snackbar.

**Comment by bkerensa** [comment]
@satya164 I really like the colors can we use icons in the circle of each one? ( @elioqoshi  feedback?) also how are those circles displayed? Are they triggered by pressing one circle that expands out into that?

**Comment by satya164** [comment]
@bkerensa Yes. Yes. I didn't use icons here since it was just a mockup, and we need to decide the icons and all.

**Comment by bkerensa** [comment]
![tool848](https://cloud.githubusercontent.com/assets/859175/11578159/cd6a8ed6-99d7-11e5-816b-0ac2ce46c0d7.png)
![blood12](https://cloud.githubusercontent.com/assets/859175/11578158/cd67b88c-99d7-11e5-9781-3776159cb39b.png)
![drop3](https://cloud.githubusercontent.com/assets/859175/11578160/cd6ba780-99d7-11e5-8583-e64ef59e6cc3.png)

**Comment by bkerensa** [comment]
Those are just some ideas the blood drop for Glucose, Cuff for Blood Pressure and Scale for Weight and for Cholesterol I might do two blood drops one with HDL and the other with LDL inside.

For Ketones I might do a drop with K inside and for HBA1C I would put "HbA1C"  I would maybe do a blood drop with a magnifying glass that says "HbA1C"  <-- btw casing matters :P

**Comment by bkerensa** [comment]
@PaoloRotolo Can you get this added the current mockup and work with @satya on any final tweaks needed land this and correct any text like the HbA1c that way we can begin l10n and then @elioqoshi says in a few days he can do the icons overlay.

**Comment by elioqoshi** [comment]
I will be at the Mozilla All Hands Meeting next week and will be available again only after 14th December.

**Comment by bkerensa** [comment]
@elioqoshi That is fine our deadline for this is at least two days before Christmas if possible.

**Comment by elioqoshi** [comment]
No problem, just ping me again on 15th Dec or so if I forget by any chance.

**Comment by elioqoshi** [comment]
First proposal

![glucosio icons](https://cloud.githubusercontent.com/assets/5436686/11977033/f4bb301a-a97e-11e5-83af-0d20980c35fa.jpg)

**Comment by elioqoshi** [comment]
Here are the final icons @PaoloRotolo 
http://elioqoshi.me/owncloud/index.php/s/UbYvKNDp32NrJRS

**Comment by bkerensa** [comment]
I'll grab these tonight too and push them to branding as we will need them for iOS too

**Comment by PaoloRotolo** [comment]
@bkerensa Can you please add Elio's icons to branding repo?

**Comment by bkerensa** [comment]
Done
