### ISSUE TITLE
Add FAQ View & Bug Reporter 

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#11]
FAQ (view) added and implement bug reporter library.

**Comment by bkerensa** [comment]
We do not need a FAQ in app we can link to this on about page

@PaoloRotolo Android has its own bug crash tool right? Should that be sufficient since we will have faq linked from about which will also tell how to report issues on GH?

**Comment by satya164** [comment]
Crash reports appear on the Google Play Store console. We could integrate something to send us emails on crashes.

Also @PaoloRotolo has written a lib to send bug reports to GitHub.

**Comment by bkerensa** [comment]
Ah lets have that lib that reports directly to GH that would be nice either this release or in a future one
