### ISSUE TITLE
Add Font Size Settings

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#112]
We should add a font size setting to allow Normal, Medium and Large font options for users with vision problems.

**Comment by piotrek1543** [comment]
I think you want add this feature having in mind old people or someone having problems with eyesight.

I don't think it would be a good idea, it could make things even worse, like rebuilding existing layouts specially for this feature. We have some more important features like integrating app with wearable devices :-)

**Comment by piotrek1543** [comment]
I think you want add this feature having in mind old people or someone having problems with eyesight.

I don't think it would be a good idea, it could make things even worse, like rebuilding existing layouts specially for this feature. We have some more important features like integrating app with wearable devices :-)

**Comment by bkerensa** [comment]
Ah ok thanks @satya164 closing

**Comment by satya164** [comment]
We don't need to add font size settings. System has a hard font setting in accessibility and Glucosio already works with it.
