### ISSUE TITLE
Add Backup to Settings

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#116]
We need a backup settings area

**Comment by issacnitin** [comment]
Do you need an entire activity or just one box for Google Drive? I'll work on it

**Comment by PaoloRotolo** [comment]
Hey @issacnitin, I think an activity would be better. Just in case we have to open it from Main/Assistant.

**Comment by issacnitin** [comment]
Cool, started working on it.

**Comment by issacnitin** [comment]
Done! :dancer:
