### ISSUE TITLE
Add Backup to Google Drive

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#117]
Our first backup option should be Google Drive since most Android users will already use Google Drive. We need a mechanism that allows one-off backup but also periodic interval backups to Google Drive. This feature should tie into the Backup Settings.

-> Settings -> Backups -> Google Drive -> Options 

Dependency: #116

**Comment by issacnitin** [comment]
Working on it

**Comment by bkerensa** [comment]
So on this we will probably want to have a Google Drive settings menu of its own and allow options: connect, interval, manual export to google drive etc. So one menu deeper and more than just a enable button.

Since the backup is already live in daily @PaoloRotolo we will need this finished before we can ship next release or will need to back out this patch and  Issue #116. We cannot ship them non-working! :)

**Comment by Aeyoun** [comment]
As Glucosio can be considered sensitive personal and medical information, I wounder if the information in backup files will be encrypted? Have this been considered?

**Comment by bkerensa** [comment]
We are only planning to support providers which use a reasonable degree of protection of backup in this case we believe Google Drive does this it offer two factor and many people store sensitive data on it already.

Adding encryption would impact portability of the data. If users want to encrypt the data when they export it storage they have that option.
