### ISSUE TITLE
I can not see the text in button. 

### ISSUE THREAD

**Issue by birajkarmakar** [Glucosio/glucosio-android#121]
Attched screenshot http://awesomescreenshot.com/0335c53d75

Even I can not scroll also.

**Comment by bkerensa** [comment]
Any update on this @PaoloRotolo

**Comment by piotrek1543** [comment]
I've added a pull request with commit fixing this problem.

**Comment by PaoloRotolo** [comment]
Fixed in latest commit.
Thanks!
