### ISSUE TITLE
Investigated Automated Testing

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#129]
Investigated calabash, AppThwack, HockeyApp and other testing frameworks or services for automated testing to find bugs before they find us ;)

**Comment by amouly** [comment]
@bkerensa what about Espresso? It's better than Calabash because it's designed for Android only.

http://developer.android.com/training/testing/ui-testing/espresso-testing.html

**Comment by piotrek1543** [comment]
I EXTREMELY recommend Espresso UI test framework - simple, fast and effective.
Here, you can see some possibilities of writing tests in this framework:
https://google.github.io/android-testing-support-library/downloads/espresso-cheat-sheet-2.1.0.pdf

**Comment by amouly** [comment]
@piotrek1543 agree. I've already started some tests based on Espresso for this project. First I have to determine what we should test. I will send a PR soon :).

**Comment by PaoloRotolo** [comment]
Fixed in latest commit.
Thanks!
