### ISSUE TITLE
Add Credits

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#131]
We will want to add a credits which lists each contributor to the project.

@satya164 we will need mockup for this and it should be in the settings somewhere.

**Comment by bkerensa** [comment]
@satya164 Can we get some feedback on this? @elioqoshi was thinking maybe the Glucosio pink drop made up of each contributors name like Cyanogenmod uses their logo with contributor names... thoughts?

**Comment by Jobava** [comment]
Can we reopen this issue?

**Comment by bkerensa** [comment]
This issue is not closed and will be addressed in our next major release
