### ISSUE TITLE
Project rename?

### ISSUE THREAD

**Issue by amouly** [Glucosio/glucosio-android#141]
Should we rename the project to "glucosio-android"? Because when an user forks it, he has to rename it anyway. Calling it just "android" it's not descriptive.

**Comment by PaoloRotolo** [comment]
@bkerensa What do you think? We can even use android package name and  call it "org.glucosio.android".

**Comment by bkerensa** [comment]
If we rename it I would rather use glucosio-android as org.glucosio.android is not very descriptive
and I do not see this much in github repos for projects.

**Comment by bkerensa** [comment]
This is now fixed

**Comment by amouly** [comment]
@bkerensa awesome! Good decision :).
