### ISSUE TITLE
Implementing SmartTabLayout instead of using ActionMenu and tabs.

### ISSUE THREAD

**Issue by piotrek1543** [Glucosio/glucosio-android#143]
Hi, I really don't like in your app combo of menu with two items and three tabs. I think it would be good to implement a view called SmartTabLayout. Here you can find it:
https://github.com/ogaclejapan/SmartTabLayout
Moreover, when I click third tab I have doubled a feedback function (the first one actually hidden as menu item, the second one as the first item on the list).
Implementing these dynamic tabs will solve this issue and improve a user experience.

**Comment by PaoloRotolo** [comment]
@piotrek1543 Thanks for your concerns about usability.
I think we can fix that as discussed with @bkerensa using a navigation drawer. It's more material-ish and integrates perfectly with TabLayout.

**Comment by piotrek1543** [comment]
@PaoloRotolo, :+1: Well, for me usability is more important than visual look ;-)
Waiting to see an effect. Now you can close issue.

**Comment by PaoloRotolo** [comment]
So, we decided to move to a Navigation Drawer. See this bug: https://github.com/Glucosio/glucosio-android/issues/144
