### ISSUE TITLE
Navigation Drawer Migration

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#144]
We will be migrating to a Navigation Drawer Layout the following work is needed:

* [ ] Add Navigation Drawer Code
* [ ] Migrate Overview, History and Assistant to Nav Drawer
* [ ] Migrate Settings to Nav Drawer

Once this is complete and we have a daily build we should take to @elioqoshi about maybe some icons to the left of each nav drawer menu label. 

Depends: #145 and #146

**Comment by satya164** [comment]
What? Why exactly?

**Comment by piotrek1543** [comment]
@bkerensa  tested that day and it looks much better that menu on the right and of course, in a future development some things from actual Settings menu like Credits or Version would be items on Navigation Drawer Menu.

**Comment by PaoloRotolo** [comment]
@bkerensa Settings and other activities (Invite and Feedback) has been migrated.
We decided to keep Overview, History and Assistnat in tabs, so what else do we add?

**Comment by amouly** [comment]
@PaoloRotolo why we are using the MikePenz library for this? Our Drawer it's pretty simple, maybe with the Support Design Library we can achieve the same functionality and not depend on extra libraries.

**Comment by PaoloRotolo** [comment]
@amouly it will become more complex later. MikePenz's drawer is well supported and maintained.
Also this means less code, we don't have to build another custom adapter for navDrawer.

**Comment by PaoloRotolo** [comment]
I'm closing the issue BTW. The new drawer is available in Glucosio 0.8.3.
