### ISSUE TITLE
Export or share

### ISSUE THREAD

**Issue by RyanGrange** [Glucosio/glucosio-android#148]
Some way of getting a subset of reading out for sharing with the doctor directly, via email, or attached to a web form post on a doctor's private web portal.  Possibly something simple like a CSV file.  (Not sure what would work across Android and IOS.)

**Comment by bkerensa** [comment]
This is definitely something we are planning for!

**Comment by piotrek1543** [comment]
@RyanGrange great idea! Sending by mail data to a doctor would have a great impact for Glucosio app future.

**Comment by lgp171188** [comment]
It would also be helpful if there is an import feature to import the export file. This makes switching between various versions of Glucosio (Daily, Stable, F-Droid) without losing all the existing data.

**Comment by bkerensa** [comment]
This is now covered in Issue #158
