### ISSUE TITLE
[Bug][Low priority] Missing "Backup" toolbar.

### ISSUE THREAD

**Issue by piotrek1543** [Glucosio/glucosio-android#149]
Hi,

I've already noticed that after clicking on "Backup" in "Options" menu I see a view with "Google Drive" checkbox, but lack of toolbar. Could you fix this with adding a simple toolbar with title and back button

Well, it's seems to be a small thing, but it could improve much more a user experience of Glucosio app.

Cheers,
Peter

**Comment by PaoloRotolo** [comment]
Hi @piotrek1543. Thanks for the issue, we'll fix it ASAP.
Please note that GDrive integration is still in development and not fully implemented.

**Comment by piotrek1543** [comment]
@PaoloRotolo, I noticed that GDrive-integration is not full supported, but I found an issues about it so I added a small one responding to a missing toolbar in that view ;-)

**Comment by PaoloRotolo** [comment]
Fixed, ty. :+1:
