### ISSUE TITLE
Don't delete items from Assistant section permanently

### ISSUE THREAD

**Issue by piotrek1543** [Glucosio/glucosio-android#152]
Hi,

I've already noticed that it is possible to remove items form Assistant following these simple steps:
1) Click and hold the item which you want to remove.
2) Move him to the left (like would you perform swiping left).

My suggest is simple - if it is possible, block these action or add an option in navigation menu set to defaults.

Look, I deleted options which might be useful in future (now I see only an empty view) and the only action to bring them back is cleaning data of app or reinstalling.

Cheers,
Piotr

**Comment by satya164** [comment]
What's the bug?

**Comment by piotrek1543** [comment]
@satya164 In Assistant section you have three items (share with friend, provide a feedback - sorry, but now I have this part empty :-D ). Performing steps as I'd already described gives you an opportunity to delete these fragments

**Comment by satya164** [comment]
@piotrek1543 Isn't that what's supposed to happen?

**Comment by piotrek1543** [comment]
<a href="http://pl.tinypic.com?ref=aauqgn" target="_blank"><img src="http://i67.tinypic.com/aauqgn.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by satya164** [comment]
Sorry, but I really understand the bug. So you're able to remove things from assistant following the steps you said. But what's the bug?

**Comment by piotrek1543** [comment]
@satya164 Sorry, maybe we have different definition for word "bug". I changed name of isssue :-D

**Comment by satya164** [comment]
@piotrek1543 Are these implented in the current version or are you suggesting to implement them?

**Comment by satya164** [comment]
Ok, so

> Deleting permanently items from Assistant section

I'm really confused, what you mean. Are you saying that you can't do it with the current version?

**Comment by piotrek1543** [comment]
well, less than a hour ago I forked glucosio-android, than run in Android Studio.

**Comment by satya164** [comment]
Yes, but what's the bug/feature request?

> I've already noticed that it is possible to remove items form Assistant following these simple steps:

What I understand from this is that it's possible to remove items from assistant with the current version of Glucosio.

I'm really confused on what's the issue. Do you suggest that we should not be able to do it? Or are you saying that this feature is broken?

**Comment by piotrek1543** [comment]
My suggest is simple - if it is possible, block these action or add an option in navigation menu set to defaults. 

Look, I deleted options which might be useful in future (now I see only an empty view) and the only action to bring them back is cleaning data of app or reinstalling.

**Comment by satya164** [comment]
@piotrek1543 Ok, got it.

@PaoloRotolo @bkerensa I think we can archive assiatnt notifications instead of removing entirely. We can have a place where one can access all archived notifications.

**Comment by satya164** [comment]
@piotrek1543 I've updated the title and the bug report to reflect what you meant.

**Comment by piotrek1543** [comment]
@satya164 Thanks a lot :-)

**Comment by satya164** [comment]
@piotrek1543 You're welcome.

**Comment by PaoloRotolo** [comment]
@piotrek1543, @satya164 nice one, I'll add a section for archived tips.

**Comment by PaoloRotolo** [comment]
@satya164 can you please suggest where to put a button to see archived tips?

**Comment by satya164** [comment]
![5-glucosio-tips](https://cloud.githubusercontent.com/assets/1174278/11020068/aa19016c-8639-11e5-951c-e48a9a0689c2.png)

**Comment by piotrek1543** [comment]
Hi @satya164 and @PaoloRotolo, can i close an issue? Has that already been fixed?

**Comment by PaoloRotolo** [comment]
I'm pushing the code right now.

**Comment by piotrek1543** [comment]
@PaoloRotolo, ok.

**Comment by PaoloRotolo** [comment]
@piotrek1543 Fixed. Try it in today's daily: http://daily.glucosio.org/

**Comment by piotrek1543** [comment]
Hi, I've already installed an app. I would test it and if it would be necessary create some notes or issues.
