### ISSUE TITLE
Add paddingDown to History section to fix problem with data hidden by FAB

### ISSUE THREAD

**Issue by piotrek1543** [Glucosio/glucosio-android#153]
Hi,

like on Overview tab in one of latest closed issues, a floating action button hides results of last examination. Let a look at a picture:
<a href="http://pl.tinypic.com?ref=rua88m" target="_blank"><img src="http://i68.tinypic.com/rua88m.jpg" border="0" alt="Image and video hosting by TinyPic" height="500"></a>

The easiest way to solve this issue is just adding paddingBottom (in Overview I added about 60dp) to layout or last item (here I would choose the first choice)

I'm also thinking as now Glucosio mobile app has navigation menu to add "+" button on the right sight of toolbar. It might be also button with text like "add test".

Cheers

**Comment by satya164** [comment]
@PaoloRotolo We should add a bottom padding in both overview and history screens.

**Comment by piotrek1543** [comment]
@satya164 As I remember I added a paddingBottom in my pull request which was merged
