### ISSUE TITLE
Dates of the readings off by a month

### ISSUE THREAD

**Issue by lgp171188** [Glucosio/glucosio-android#155]
I use version 0.8.0 (Noce) of Glucosio on my OnePlus One. I noticed that whenever I enter a reading with a particular date, the actual stored date is off by a month. For example, October 31 2015 got saved as 1 December 2015. This makes Glucosio totally useless for me.

**Comment by PaoloRotolo** [comment]
Hi @lgp171188!
We fixed the issue in Glucosio 0.8.1. Please update :)

**Comment by lgp171188** [comment]
Thanks for the update! I had installed it from F-Droid and there were no updates. After uninstalling the F-Droid version and installing the stable version from this repository, it is working fine :)

**Comment by lgp171188** [comment]
But the version always says 0.8.0 (Noce) even with the 0.8.2 version which is very confusing and misleading. Is this a known issue? If not, I will raise a new issue

**Comment by PaoloRotolo** [comment]
@lgp171188 Yes, please check App info for version number.
Unfortunately for a bug, minor releases aren't displayed in settings.

![screenshot_2015-11-05-17-02-51](https://cloud.githubusercontent.com/assets/5623301/10973780/33a9a79a-83df-11e5-9206-ee5f82352921.png)
