### ISSUE TITLE
Add Import to Settings`

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#158]
Feature Requirements:
- Export to CSV (Download or Option to use Android Share Menu)
- Import from CSV 

As we add backup options like Google Drive and others we should allow export of CSV to those platforms through this menu and import from those sources too.

**Comment by bkerensa** [comment]
@PaoloRotolo What kind of text did you need here? Might need some context

**Comment by PaoloRotolo** [comment]
@satya164 can you please provide a better design for Export Activity? I guess the actual design has a lot of free space.

![screenshot_2015-12-01-17-27-58](https://cloud.githubusercontent.com/assets/5623301/11506724/19ccc984-9851-11e5-9de0-23de7320152b.png)

![screenshot_2015-12-01-17-28-01](https://cloud.githubusercontent.com/assets/5623301/11506723/19cb0d6a-9851-11e5-8692-ddb5bd3b26d5.png)

**Comment by satya164** [comment]
We really don't need an Activity for this (at least not yet). A simple dialog will be enough.

![img_20151203_131601](https://cloud.githubusercontent.com/assets/1174278/11554712/7a2eaa48-99c0-11e5-8126-e5c1df9426c9.jpg)

**Comment by satya164** [comment]
Also, if I've selected "Export Range" and not specified the dates, then the "Export" button should be disabled. Right now it says "Exporting 0 readings..." or something.

The exported file name should be something like "gulcosio-export-data-${fromdate}-${todate}". Right now it's -18728 something.

**Comment by Flameeyes** [comment]
Hi, I've been pointed at this Issue from my repository [glucometerutils](https://github.com/Flameeyes/glucometerutils) (simple script to dump data out of various glucometers I have here, some of which I [reverse engineered myself](https://github.com/Flameeyes/glucometer-protocols/).

I've been given an example of data export, but it does make me wonder quite a bit, particularly:

 * date format: why not use [*the* correct way to write numeric date](https://xkcd.com/1179/) aka ISO 8601? Possibly merging date and time into a single field, and extending to seconds (many meters do report seconds.)
 * is mmol/L the only/default export option? while this is the theoretical standard (and I'm used to it by living in IE), it is not what most glucometers store internally — indeed out of five protocols I implemented (all of them for UK/IE meters, which use mmol/L on display), only the one that really isn't a protocol uses mmol/L (Accu-Chek Mobile in parsing reports.)
 * there should be a way to provide extended information, structured or unstructured — most meters allow to say whether a reading is before or after meal, others even allow annotations, even *custom* annotations in one of my devices.

I would love if we could come up with a standard interchange format here, as it'd make better use of the code I wrote up to now :)

**Comment by bkerensa** [comment]
@PaoloRotolo we should target Import for 1.0

**Comment by Flameeyes** [comment]
Since I had some time to think this through (and I have now a growing collection of different glucometers at hand, probably more than it's healthy), I started defining a general exchange format with some structure and some unstructure: https://github.com/Flameeyes/gdef

I would really like to come to a single data format for exchanging this kind of data, and if someone has suggestions/improvements/critiques of the format, I'm happy to hear :)

**Comment by bkerensa** [comment]
@Flameeyes This is something we are working on too and hope to announce in the coming months which is a open diabetes data spec which other open source projects and vendors can contribute to.

**Comment by Flameeyes** [comment]
Any reason not to work together on this? I might actually have the most
devices reverse engineered or implemented, so I'd argue I have plenty of
experience on this one.

On Sat, 2 Apr 2016, 22:36 Benjamin Kerensa, <notifications@github.com>
wrote:

> @Flameeyes <https://github.com/Flameeyes> This is something we are
> working on too and hope to announce in the coming months which is a open
> diabetes data spec which other open source projects and vendors can
> contribute to.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Glucosio/glucosio-android/issues/158#issuecomment-204807694>
>
-- 
Diego Elio Pettenò (aka Flameeyes)

**Comment by bkerensa** [comment]
@Flameeyes The specification we hope to turn into a standard versus another spec that is just used by us or another app or two. Right now there is no standardization and so we hope to bring other OSS projects surrounding diabetes into supporting one standard and it would be an open collaborative effort.

**Comment by Flameeyes** [comment]
Yes and that's my hope too. Unless you have a longer list than mine, there
aren't that many more projects than yours, mine, OpenGlucose, GGC and a
couple of ad hocs.

I *was* handing a "let's work together on this", which you seem to clearly
want to avoid versus a "we'll do it and you'll accept it" which I found
uselessly confrontational.

But so be it, I guess I won't come any closer to your project in the future.

On Sat, 2 Apr 2016, 22:43 Benjamin Kerensa, <notifications@github.com>
wrote:

> @Flameeyes <https://github.com/Flameeyes> The specification we hope to
> turn into a standard versus another spec that is just used by us or another
> app or two. Right now there is no standardization and so we hope to bring
> other OSS projects surrounding diabetes into supporting one standard and it
> would be an open collaborative effort.
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/Glucosio/glucosio-android/issues/158#issuecomment-204808255>
>
-- 
Diego Elio Pettenò (aka Flameeyes)

**Comment by bkerensa** [comment]
There is Nightscout, Tidepool those are two other big ones for sure but we're also establishing hardware vendor partnerships too so we can use that to leverage some standardization.

**Comment by bkerensa** [comment]
"I *was* handing a "let's work together on this", which you seem to clearly
want to avoid versus a "we'll do it and you'll accept it" which I found
uselessly confrontational.""

You commented a couple days ago about this prototype your working on we've been working on a concept since year. We've always planned on having our own in house developed spec that we would try and turn into a standard. There is nothing confrontational about this and I don't understand why your upset that we already have plans and are not interested in working on your prototype.

As a project we decide what works best for us and we're trying to minimize use of libraries and specs that are created by third parties who could disappear tomorrow.

**Comment by chrispecoraro** [comment]
http://xkcd.com/927

**Comment by bkerensa** [comment]
😀
