### ISSUE TITLE
Clicking on graph legend would open a custom info dialog with values

### ISSUE THREAD

**Issue by piotrek1543** [Glucosio/glucosio-android#160]
Hi,

I'm already testing Glucosio-Daily downloaded from website as @PaoloRotolo suggested me. I noticed nice-looking graph with colourful points, which I can click to get a scale to another values. 

I think it would be a good idea if after clicking on bar with colors and names like Hypoglycemia it would show an info dialog with values for every item. It may improve a little a user experience, much more testing. For clear example, I can't get a blue color, described as "Low" and before testing I cannot guess the lowest and highest possible values.

What do you think about this idea?

Cheers.

**Comment by bkerensa** [comment]
@piotrek1543 Probably good to discuss this in #98 I had suggested a legend/information market that opens on tap.

**Comment by piotrek1543** [comment]
@bkerensa please reference this issue with #98. After this, I think you can close it.
