### ISSUE TITLE
Date and time picker widgets always show the current date and time even when they have data

### ISSUE THREAD

**Issue by lgp171188** [Glucosio/glucosio-android#165]
I'm running Glucosio version 0.8.3 installed from the Google Play Store. When entering a reading, it is possible to select the date and time from the widgets provided. If I entered a date/time and want to edit it again, it always defaults to current date/time instead of the current value in the field which is not very intuitive.

**Comment by PaoloRotolo** [comment]
You're using an old version of Glucosio. Latest one is 0.12.0.
