### ISSUE TITLE
Show the reading value when clicking on a point in the graph

### ISSUE THREAD

**Issue by lgp171188** [Glucosio/glucosio-android#168]
***1 Upvote*** The graphs are very useful to see the ranges and variations in blood sugar readings, but when clicking on a single reading (represented by a point) in the graph, it will great if some information about the reading (at least the reading value) is shown as a tooltip. Right now it just shows 2 lines touching the axes which is not very helpful.

**Comment by satya164** [comment]
+1

**Comment by bkerensa** [comment]
Fixed
