### ISSUE TITLE
Nepal missing from country list upon setup

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#170]
Comment from Social Media

**Comment by bkerensa** [comment]
Looking over our code I do not see any country strings and see this:
ArrayList<String> countries = new ArrayList<>();
Locale[] locales = Locale.getAvailableLocales();


So it appears we get the array from Android? If so they left out Nepal and this in addition to their language fragmentation is another reason we might have to DIY.

**Comment by bkerensa** [comment]
@PaoloRotolo Can you investigate this some

**Comment by PaoloRotolo** [comment]
Nepal is present in Android 6.0 stock, CM12 and CM13. It's probably something ROM specific.

**Comment by bkerensa** [comment]
Closing this but if it reoccurs we can reopen
