### ISSUE TITLE
Albanian Language 

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#172]
Albanian is supported in Android but due to some bug the locale is not shipped in all versions of Android. 

Tracking upstream in https://code.google.com/p/android/issues/detail?id=194912 and https://code.google.com/p/android/issues/detail?id=166426

Although if we fix issue #99 we can just circle around Android's locale system do our own thing and support all languages since Android's locale system is flaky.

**Comment by elioqoshi** [comment]
Having a close eye on this. Can't promote Glucosio without it being in Albanian...

**Comment by bkerensa** [comment]
@satya164 So this is a bug in Android not much we can do about it since Android does not support the Albanian language. Since a majority of Android apps rely on Android's locale system since a language switcher is somewhat buggy to implement that means I do not think there is any Glucose app currently that supports Albanian because the platform doesn't support it.

Google basically told us they do not consider this language to be a priority.

**Comment by satya164** [comment]
@bkerensa How hard is it to implement our own language switcher?

**Comment by bkerensa** [comment]
Pretty hard Paolo has been trying for two months now. Android isn't built for you to go around its locale system.

Everything he has tried has failed and he has sought advice of other android secs and their code didn't work either

**Comment by satya164** [comment]
That's sad. So what are we gonna do?

**Comment by bkerensa** [comment]
Still investigating workarounds

**Comment by bkerensa** [comment]
Since this really is on Google and they are releasing a fix for Android N going to close this
