### ISSUE TITLE
Grey 20px bar at bottom while scrolling in history view

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#175]
The height of the scrollable view doesn't fit the parent view so there is a grey bar at the bottom of history view when scrolling downwards.

**Comment by piotrek1543** [comment]
@Aeyoun it's always a good practice to add at least one screenshot describing the problem. Is it possible to do?

**Comment by bkerensa** [comment]
Absent response from reported and screenshot will close this but please reopen if it is still and issue.
