### ISSUE TITLE
Add floating "Undo" after deleting, allowing some 20 sec to undo

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#177]
Many apps have a floating black overlay with an "Undo" link to undo accidental deletes. Glucosio should have the same. When deleting, hide the item from History and wait for the overlay to disappear before actually removing the data point.

**Comment by bkerensa** [comment]
Great idea we will get this added in 0.9.0

**Comment by PaoloRotolo** [comment]
Hey @Aeyoun. We already have a Snackbar with an Undo buttons that appears after a reading is deleted.

**Comment by satya164** [comment]
Closing since we already have this. Let's reopen if I'm wrong.
