### ISSUE TITLE
Add timestamp to "Last check" on overview

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#180]
The overview page displays the last check value. But when was this measurement taken? Please include a relative timestamp "3 hours ago", "70 minutes ago" to actually give me a quick overview.

**Comment by bkerensa** [comment]
Time stamp is available in history

**Comment by Aeyoun** [comment]
I know. However, when I open the app it takes me to overview page which shows me my last measurement. A relative time stamp next to that value would help me determine whether it's time to take a new measurement or not.

**Comment by bkerensa** [comment]
@PaoloRotolo Let's see if we can do this for 0.8.4 this should be priority two so lets make sure we get the other work done first were tracking for 0.8.4 but if we can get this in then do it.

**Comment by PaoloRotolo** [comment]
Done.

![screenshot from 2015-12-05 20-56-29](https://cloud.githubusercontent.com/assets/5623301/11609887/b0eaec62-9b92-11e5-8d8c-6085d0891973.png)

**Comment by Aeyoun** [comment]
Thank you. :+1:

**Comment by bkerensa** [comment]
@Aeyoun maybe we will soon earn a four or five star play review from you!

**Comment by Aeyoun** [comment]
@bkerensa, my Play Store review reflects the current publicly released version. Without data import/export I’ll consider the app more of a toy than a long-term glucose management/insights tracking thingy. I assumed the project is aiming for the latter and it seems to be getting there. My phones have a tendency to die fairly often so … yeah, need a way to backup data.

Once the assistant starts congratulating me on lowering my weekly average from last week I’ll do a proper review on my blog too. Looking at my data, what I should be focusing on is lowering my levels after meals — and the app should tell me that rather than I having to analyze the data trends myself. That would be something worth blogging about — and probably worth more stars on Google Play.

**Comment by bkerensa** [comment]
The import and export should be release closer to Christmas as we're trying to bundle a few more features into the 0.8.4 release.

The 0.9.0 or 1.0.0 release will probably start landing significant changes to assistant. This bit takes a lot more work so will be done in pieces and take more time plus we have to comply with regulations and be careful about messaging and make sure it gets reviewed by an attorney.

**Comment by Aeyoun** [comment]
I thought about the legal implications. An EULA should help protect against liability. Then again, I know Americans get a bit overeager about suing each other all the time.

Although, starting out by pointing out where/when there is room for improvement (without specifying how to improve them) really shouldn’t be an issue. If you write things like "take more insulin" could get tricky but saying "your glucose levels usually goes too high after breakfast. you should look into that." should be all fine. Then again, someone registering nothing but high levels throughout the day every day for a month should get direct medical advice in the form "go visit a diabetics specialist tomorrow and show them the data you've recorded in this app."

**Comment by bkerensa** [comment]
Right and this is why we're evaluating all messaging through through legal first to protect ourselves as a project since we wouldn't have the means to defend against lawsuits or even fines since we don't make any money from the project. Where many other apps sell user data, monetize through ads or charge for the apps and might have the revenue to take more risk.
