### ISSUE TITLE
Import data from meters using camera OCR

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#186]
This is a high flying idea for a later version. I already hate the app. It’s not really the app’s fault but I just don’t like having to manually add values to the meter all the time. If I forget to add a reading it feels like a huge effort having to go back later and add it.

Most meter have big, backlit, and clear displays using huge fonts for test values and timestamps for accessibility reasons. It should be possible to use optical character recognition (OCR) to read the values directly off the meter and record them in Glucosio. This should make adding test results faster. It could also be possible to add multiple values.

This would also give Glucosio a better first-time user experience as new users can easily import months worth of data by holding their cameras pointed at their meters, pulling up their meter’s logbook, and cycling through values with the "previous value" button.

Should work with pretty much any meter given Glucosios ability to identify the main reading (huge number in one of two formats) and various date formats in close proximity to the reading. All users have devices with cameras and all users have meters with screens designed to be big and easy to read. Sounds like a perfect albeit totally accidental match of technologies.

**Comment by PaoloRotolo** [comment]
Please comment on bug #106. This looks like duplicate.
