### ISSUE TITLE
Allow comma as decimal separator

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#187]
My device’s default keyboard, the Sony Xperia Keyboard, only has a comma but not period for use as a decimal separator. I’m in a region that uses commas instead of periods and naturally I’d appreciate to enter values with a comma. (The split between the two decimal separators is roughly [50%/50%](https://www.slightfuture.com/webdev/html5-input-number-localization.html) – the split goes between former British colonies plus China, and then everyone else).

The international standard is “1 000,00” (ISO 31-0) and the way discouraged by all standards bodies but is still used in half the world is variants on “1,000.00”. As all glucose levels any user would ever record values  less than a thousand, the thousand separator problem can be avoided and Glucosio can **accept periods and commas interchangeably in user input.** Assuming the right-most comma or period as the decimal separator and stripping any other periods and commas should also work.

**Comment by TimothyCuffe** [comment]
Maybe add an option in the settings menu for Decimal separators? That way everything could easily be switched back and forth?

**Comment by Aeyoun** [comment]
Should at least respect the locale setting. Though, ideally it should just accept both variants no questions asked. Would anyone really insert a thousand separator in the value ranges expected by this app?

**Comment by betsythefc** [comment]
The only problem I see with this is the CSV export. We would need to surround all decimal numbers with quotes so that any spreadsheet/CSV reader will know it's not a new cell.

**Comment by Aeyoun** [comment]
@betsythefc, this issue doesn’t affect how data is stored internally or exported. This is about the localization of the user interface and user provided input.

**Comment by bkerensa** [comment]
@PaoloRotolo Lets try to land a fix for this and the CSV export decimal issue in our next release.

**Comment by emartynov** [comment]
Addressed in #307. Fixed!
