### ISSUE TITLE
Don’t allow registering the same measurement at the same time more than once 

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#191]
1. Add a measurement at 13:00 today
2. Add the same measurement at 13:00 today again

Expected: Shouldn’t let you do that as you already have the value registered.

**Comment by satya164** [comment]
+1

**Comment by bkerensa** [comment]
In fact we should add a toast error

"You already have an entry for this time. Please delete it in history and try again"

Or something like that

**Comment by Aeyoun** [comment]
Dno’t block multiple measurements for the same time. Users could doubt it and recheck. But having the exact same measurement for the same time is an indicator of user error.

**Comment by satya164** [comment]
We should show a warning in both cases. Mostly it'll be a user error. If the values are different, we can ask to replace the existing value.

**Comment by Aeyoun** [comment]
Introduced regression #201.
