### ISSUE TITLE
Click on FAB picked up by the drop-down underneath it

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#193]
Clicking on the floating action button in [screenshot 1](https://cloud.githubusercontent.com/assets/1102886/12142424/480009e0-b478-11e5-9b32-ede0828da9af.png) is sent to the drop-down list below it resulting in [screenshot 2](https://cloud.githubusercontent.com/assets/1102886/12142425/4802f790-b478-11e5-9ab9-c6b1cb4105c6.png). Started happening in the new version 0.9.0 that I got through Google Play Store today.

**Comment by PaoloRotolo** [comment]
Hey, I've just updated a patched version to Google Play (0.9.1) that should fix the issue.
Thanks!

**Comment by Aeyoun** [comment]
Thanks, I got the update just now. But I don’t think hiding the FAB is the right solution. It makes it more awkward and time consuming to add new readings.

**Comment by PaoloRotolo** [comment]
I know, this is just a temporary fix. We will release a new patch version with duplicate entry check and other fixes soon.

**Comment by PaoloRotolo** [comment]
@satya164 will provide some mockups to fix this with a better UI.

**Comment by Aeyoun** [comment]
Another regression with the current build's workaround: Have two click the FAB twice to add a reading. The button seem to get into pressed state on the first press and then actually submitted the click on the second click.

**Comment by satya164** [comment]
Sorry @PaoloRotolo for the delay. Will work in it tomorrow morning. Please ping me on Telegram.

**Comment by PaoloRotolo** [comment]
Fixed in latest commit.

![screenshot_20160425-193547](https://cloud.githubusercontent.com/assets/5623301/14793559/1d62a5b8-0b20-11e6-8528-2bbeb62b8177.png)
