### ISSUE TITLE
Terrible performance in latest version

### ISSUE THREAD

**Issue by Aeyoun** [Glucosio/glucosio-android#195]
I can’t scroll in History anymore. Scrolls one or two items than stutters and paints one row of pixels at a time before stopping entirely. Takes a good three-seconds to after clicking filling in a reading and confirming input before the add-reading activity disappears. The graph in overview takes 2–10 seconds to draw. This was not a problem before. I’ve got 317 readings in total over three .

From just looking it, scrolling seems to freeze pretty much exactly when an entry becomes 50% covered by the new drop-down selector at the top of the history activity.

I can zoom and scroll around in the overview graph just fine, but the initial painting of the graph is really slow.

**Comment by bkerensa** [comment]
Please edit your bug to use the following format:
https://github.com/Glucosio/project-tools/blob/master/gh/templates/issue_template.md

**Comment by Aeyoun** [comment]
en-us locale, nb-no keyboard, mmol/L, Sony Xperia Z3, Android 6.0.1, Google Play Store (since I can’t move data from GPS to F-Droid yet)

Catlog while scrolling in history view:

Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
art     : Background partial concurrent mark sweep GC freed 361816(12MB) AllocSpace objects, 0(0B) LOS objects, 31% free, 34MB/50MB, paused 11.199ms total 241.468ms
art     : Background sticky concurrent mark sweep GC freed 337080(11MB) AllocSpace objects, 0(0B) LOS objects, 19% free, 40MB/50MB, paused 66.127ms total 233.616ms
Choreographer: Skipped 46 frames!  The application may be doing too much work on its main thread.
art     : Background sticky concurrent mark sweep GC freed 406688(13MB) AllocSpace objects, 0(0B) LOS objects, 22% free, 41MB/53MB, paused 20.835ms total 255.071ms
Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.

**Comment by bkerensa** [comment]
@PaoloRotolo Assigning to you but I will try and grab my logs from test devices today and see if I can reproduce.

**Comment by PaoloRotolo** [comment]
I can confirm it on my Moto G. I'm working to find out what's causing the issue in the new adapter.

**Comment by PaoloRotolo** [comment]
@Aeyoun This is now fixed in 0.9.2. Can you confirm?

**Comment by Aeyoun** [comment]
Smooth scrolling in the latest build.
