### ISSUE TITLE
Use Locale Time and Date Formats

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#202]
I noticed in the date picker when adding value that it is still using ISO 8601 formatting instead of the U.S. date format: https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States#Date

So what I see is YYYY-DD-MM but U.S. uses MM-DD-YYYY or MM-DD-YY and we should also make sure we are respecting date and time formats for all android supported locales. That said I think U.S. is the akward duck and that most other countries use ISO 8601... We make up our own standards ;)

**Comment by PaoloRotolo** [comment]
Thanks, this should be fixed now.
