### ISSUE TITLE
Glucose no have low level

### ISSUE THREAD

**Issue by weslly99** [Glucosio/glucosio-android#204]
Glucose Level
69 mg/dL = Hypoglycemia
70 mg/dL = OK
181 mg/dL = High
201 mg/dL = Hyperglycemia

? = Low

**Comment by PaoloRotolo** [comment]
Hypo and Hyper are fixed values: 70 mg/dL and 200 mg/dL.
Low and High depends on the configuration you've selected in settings:
ADA: 70 - 180
AACE: 110 - 140
UK NICE: 72 - 153

You can also set custom values for low and high in settings.

**Comment by weslly99** [comment]
Thank you :)
