### ISSUE TITLE
Option to invite someone to use the app is gone but still shown in code

### ISSUE THREAD

**Issue by MarkOSullivan94** [Glucosio/glucosio-android#205]
Just reading through the code and I've noticed that within the onItemClick (line 169 of MainActivity.java) method you've got an option for when item5 is clicked but in the most recent version of Glucosio that I have downloaded, it only has 5 items and the invite item is no longer there in the app.

Just wondering if it's been decided to remove that feature or if it's accidentally missing.

Also, your ordering within the method goes item1 -> item3 -> item4 -> item5 -> item2 -> item6. Just a slight annoyance of mine :smiley:

**Comment by PaoloRotolo** [comment]
Hi @MarkOSullivan94. Thanks for the report.
It seems invite feature was removed for testing but never reintroduced again. I've added it back and refactored the items' name to correct order. ;)

Have a good day.
