### ISSUE TITLE
HBA1C preferred unit

### ISSUE THREAD

**Issue by TimothyCuffe** [Glucosio/glucosio-android#208]
Recently, my hospital has changed to giving HBA1C readings in mmol/mol, as opposed to %.

The "Preferred unit" in the settings menu only refers to glucose readings. Maybe it should be changed to 'BG unit'.

An independent setting 'HBA1C unit' should also be available, giving % and mmol/mol as an option.

**Comment by PaoloRotolo** [comment]
Thanks, I'm on it to add the feature in next release.

**Comment by PaoloRotolo** [comment]
Done, you can try it now on Glucosio Daily channel.
