### ISSUE TITLE
Weight tracking units

### ISSUE THREAD

**Issue by chwalters** [Glucosio/glucosio-android#218]
Weight tracking units should chosen by the user, not always specified as metric but also allow imperial

**Comment by prakharmohan0809** [comment]
Stone and pound or just pound?

**Comment by bkerensa** [comment]
We would do kilograms and pounds as stone is not an official measurement under any standard.

**Comment by PaoloRotolo** [comment]
Ok, I'm on it.

**Comment by PaoloRotolo** [comment]
Pound unit is now available in Glucosio Daily and will be released to prod with Glucosio 0.10.4.
Thanks.
