### ISSUE TITLE
Notes overflows over save 

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#224]
If you hit return constantly it expands the note field past the check/save icon and the reading cannot be saved

**Comment by bkerensa** [comment]
![screenshot_20160412-005306](https://cloud.githubusercontent.com/assets/859175/14453397/734068d0-0049-11e6-8721-c239a6eb3d50.png)

**Comment by emartynov** [comment]
What about moving action button on top? 
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7S2NiZlNhcDUxSTA/patterns_actions_fab_content2.png

**Comment by PaoloRotolo** [comment]
I think moving it top is the best solution too. This could also fix our "keyboard" bug, where the keyboard hides the fab when expanded. @satya164?

**Comment by satya164** [comment]
We've two solutions,

1. Move it to top
2. Add a fixed bar at the bottom like twitter does

**Comment by PaoloRotolo** [comment]
I would vote to move it on the top to keep consistency with other activities.

**Comment by PaoloRotolo** [comment]
Fixed in latest commit. 

![screenshot_20160425-193547](https://cloud.githubusercontent.com/assets/5623301/14793502/bcad054c-0b1f-11e6-82f6-6a413ed8307d.png)
