### ISSUE TITLE
Daily backups

### ISSUE THREAD

**Issue by ploctaux** [Glucosio/glucosio-android#231]
Is it possible to perform a daily backup so that users can forget about doing backups before they loose their device or something like that?

**Comment by PaoloRotolo** [comment]
Yes, automatic backups is on the ToDo list for next releases.

**Comment by ploctaux** [comment]
Sweet! :)

--
Philippe Loctaux <phil@philippeloctaux.com>

**Comment by satya164** [comment]
Ideally, we should do the backup after every new entry.

**Comment by PaoloRotolo** [comment]
Ok I'm closing this since #239 is similar.
