### ISSUE TITLE
Create Automatic Sync

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#239]
We now have backup to Google Drive which users can do manually but we need something automated for the end user. So building off this manual backup support we should look into expanding that UI and the backend code to automatically sync and also be able to easily support more backup providers.

Requirements: 
- Expand Existing Backup UI with Sync Option
- Support for Google Drive Initially (Other Providers Later)
- Sync Runs After Each Data Entry and Once Per Day in Background

**Comment by bkerensa** [comment]
@PaoloRotolo @emartynov I'd like you both to collaborate on this essentially we need the option to have automatic backups and the current manual and let end user configure whether they would like automatic or to just do it manually. We also need to make our current backup code plus automatic syncing code provider agnostic so we can easily hook in other storage providers like box.com or dropbox.com or NextCloud etc.

**Comment by JoaquimLey** [comment]
@bkerensa If both @PaoloRotolo  and @emartynov haven't started on this I could take this feature up. It will envolve a lot of code refactoring though especially on the [BackupActivity](https://github.com/Glucosio/glucosio-android/blob/develop/app/src/main/java/org/glucosio/android/activity/BackupActivity.java).

**Comment by bkerensa** [comment]
@JoaquimLey It is all yours! :) we need the sync to be able to allow other backup providers in the future but for now just Google Drive

**Comment by JoaquimLey** [comment]
@bkerensa Do you have gave the required permissions on the Google App/Api end?

**Comment by bkerensa** [comment]
@PaoloRotolo Can you mentor Joaquim on Slack on this bug

**Comment by JoaquimLey** [comment]
@bkerense I don't think (at least for the time being) I need help, the code is ready, just need you guys to enable the auth ou the GoogleApp/API end :)
But thanks!

**Comment by g33kdad** [comment]
I would love to see webDav support. I would use my ownCloud/Nextcloud server.

**Comment by ghost** [comment]
@paolo
