### ISSUE TITLE
App forces user to English language

### ISSUE THREAD

**Issue by emartynov** [Glucosio/glucosio-android#244]
Review from Google play:

> Where did the Czech? After updating disappeared Czech language.

**Comment by emartynov** [comment]
We should add also language to `HelloActivity`. Otherwise, people who can not understand English will not pass it or will not be able to open Preferences

**Comment by PaoloRotolo** [comment]
Yes after we fix the issue, the best option is delete the language settings in Database, then create a variable in SharedPreferences. Finally, check on start if the variable is created, so we don't delete data each time.

**Comment by emartynov** [comment]
Will be released soon
