### ISSUE TITLE
Can't save glucose levels anymore

### ISSUE THREAD

**Issue by fethomm** [Glucosio/glucosio-android#251]
With the latest update I cannot see the little tick that used to show to save a glucose level that I added. I can't find a way to save my entries anymore.  This is with Android 4.4.2 on a Samsung Galaxy Neo. If you need more info, I will be happy to provide it.

**Comment by emartynov** [comment]
Are you about this:
![tick](https://cloud.githubusercontent.com/assets/295424/16541998/abada740-4096-11e6-9c37-4f2c08bd1cd2.jpg)

**Comment by fethomm** [comment]
yes, and it is fixed already. :)

Am 02.07.2016 20:51 schrieb Eugen Martynov: 

> Are you about this:
> [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/295424/16541998/abada740-4096-11e6-9c37-4f2c08bd1cd2.jpg
[2]
https://github.com/Glucosio/glucosio-android/issues/251#issuecomment-230116528
[3]
https://github.com/notifications/unsubscribe/AOcQfYXgagX6GzI8GoMIBRdwG8WhLYz_ks5qRrMZgaJpZM4JDtiU

**Comment by emartynov** [comment]
Closing it for now
