### ISSUE TITLE
Update F-Droid repo

### ISSUE THREAD

**Issue by betsythefc** [Glucosio/glucosio-android#256]
The latest version of Glucosio on F-droid is 0.8.1
The latest version of Glucosio on Google Play is 1.1.1

**Comment by PaoloRotolo** [comment]
We decided to create a new FOSS-only branch (since Glucosio includes proprietary elements like Google Drive backup API): https://github.com/Glucosio/glucosio-android/tree/foss-only

Now we're waiting for F-Droid to upload a new release.

**Comment by PaoloRotolo** [comment]
Please refer to #219 for updates.
