### ISSUE TITLE
"Export range" displays in English

### ISSUE THREAD

**Issue by TonnesM** [Glucosio/glucosio-android#257]
The "Export range" string keeps displaying in English even though it’s localized for several locales.
https://crowdin.com/translate/glucosio/1/en-enus#q=export+range

While at it, a l10n note about this being intended as a noun (i.e. "the range to export", not "exporting a range") would be welcome, since some localizations appear to use the latter.

**Comment by PaoloRotolo** [comment]
Thanks, we committed a fix that will be available in next release.
