### ISSUE TITLE
Weight edition open Glucemy editor

### ISSUE THREAD

**Issue by HarKoss** [Glucosio/glucosio-android#258]
Hi,

It look like we can only edit glycaemia in the history tab. 
I saw in the HistoryFragment that OnClickListener only create AddGlucoseActivity.

Can I help fixing this one ?

### Steps to reproduce
1. Open History tab
2. Select Body Weight
3. Long old an item of the list
4. Press Edit

### Expected behaviour
Open "Edit Body Weight reading" dialog

### Actual behaviour
Open "Edit Glucose reading" dialog

**What language/locale is your device set to use?:** French
**What measurement system are you using:**  kg and mg/dL
**Are you using backups:** no

### Device configuration
**Device:** Crosscall Trekker-x1
**Operating system:**Android
**Operating system version:**4.4.2
**Downloaded App From:** playStore, also test the github (develop) version

**Comment by PaoloRotolo** [comment]
Yes, the edit option should not be available at all on not glucose readings since it's not implemented yet.

**Comment by HarKoss** [comment]
I checked my phone app version is 1.1.1. Is this the testing version or the released one ?
On this version, when I long press on a weight entry, it opens the menu to edit or delete it. And press edit open the "Edit Glucose reading" dialog.
Should it be fixed quickly or in the next release ?

**Comment by PaoloRotolo** [comment]
Fixed in latest commit.
