### ISSUE TITLE
Exported CSV file always is empty

### ISSUE THREAD

**Issue by Ghazghkull** [Glucosio/glucosio-android#264]
Every time I launch the option of export csv, the app generates an empty csv file :(

**Comment by PaoloRotolo** [comment]
We're working on it. Actually Export doesn't work for some devices and we're trying to fix the issue ASAP.

**Comment by PaoloRotolo** [comment]
Please see bug #253

**Comment by Ghazghkull** [comment]
Ok thanks.  I'm diabetic and also Java developer. If I can help you....

**Comment by PaoloRotolo** [comment]
@Ghazghkull cool, join us on Slack so we can talk about it: http://slack.glucosio.org/

**Comment by Ghazghkull** [comment]
I'm joined, but it is the first time I can review the project ;)
