### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by djKooks** [Glucosio/glucosio-android#269]
I got a problem when import project on Android Studio(2.1.2).
```
Error:Cause: com/android/build/gradle/internal/model/DefaultAndroidProject : Unsupported major.minor version 52.0
```
My jdk version is 1.8.0.
Does anyone know about same problem?

**Comment by emartynov** [comment]
I'm surprised that you can use alpha version of android gradle plugin with stable version of android studio:

http://stackoverflow.com/questions/37466744/android-studio-continues-to-get-a-unsupported-major-minor-version-52-0

**Comment by djKooks** [comment]
@emartynov Do I need to use stable gradle plugin?

**Comment by djKooks** [comment]
I just check the comment on gradle setting to fix version when using it.
```
dependencies {
        // TODO: Please revert to a stable gradle version before releasing on prod
        // Alpha is required in devel to use Instant Run and speed up development process
        classpath 'com.android.tools.build:gradle:2.2.0-alpha5'
```
It worked well after I changed gradle version to 2.1.2.
Thanks for help.

**Comment by emartynov** [comment]
Closing as not relevant!
