### ISSUE TITLE
Settings only able to display Type 1 and Type 2, Preferred range may also fail

### ISSUE THREAD

**Issue by TonnesM** [Glucosio/glucosio-android#288]
When changing the diabetes type from Type 1 to either Gestational or LADA, Type 2 is always displayed as a result. Not sure how it't treated by the app, but it should of course display either Gestational or LADA.

This happens when e.g. type 2 was chosen during install. When choosing Gestational during install however, it shows "Type 3" afterwards in Settings, but then the same thing happens when changing it. Similar results occur when choosing LADA during install: Type 4 changes to Type 2 afterwards.

While at it, the Preferred range shows no type at all in settings, so can't see what's been selected, nor if that's remembered correctly, though it might fail since the Min and Max value don't change when selecting Custom range.

**Comment by bkerensa** [comment]
Please file the preferred range as a separate issue.

Thanks

**Comment by TonnesM** [comment]
I should have known. ;) See #289.
