### ISSUE TITLE
Preferred range not displayed in Settings when selected

### ISSUE THREAD

**Issue by TonnesM** [Glucosio/glucosio-android#289]
(originated from issue #288)

In Settings screen, the Preferred range does not display what's been selected, nor if that's remembered correctly. Any change in units may also fail since the Min and Max value don't change / remain grayed out when selecting Custom range.

**Comment by edda92** [comment]
Hi guys! i'm taking care of it!

**Comment by bkerensa** [comment]
@edda92 Excellent thanks!

**Comment by riskysnail** [comment]
The selected preferred range is still not displayed in the preferences. I've got a fix ready though and will request a pull soon.
