### ISSUE TITLE
Hello View and Settings display only English 

### ISSUE THREAD

**Issue by goldleon** [Glucosio/glucosio-android#297]
How Can I add more languages to display in the languages select?

**Comment by emartynov** [comment]
Which language do you want to add?

**Comment by goldleon** [comment]
I want to add arabic and french please

**Comment by bkerensa** [comment]
@goldleon are you saying the translations french and arabic are not available for you? If that is the case we can always use l10n contributions at http://translate.glucosio.org

**Comment by emartynov** [comment]
It looks like both languages near 100% translated. I suppose the issue that user doesn't see these languages in language selector in settings.

**Comment by goldleon** [comment]
Yes @emartynov exactly. th language selector in settings show always and only english
