### ISSUE TITLE
Add Launcher Shortcuts

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#299]
We should try and add launcher shortcuts for adding metrics to Glucosio:
http://www.androidpolice.com/2016/04/21/android-n-feature-spotlight-launcher-shortcuts-give-apps-many-new-ways-to-provide-information-and-quick-actions/

**Comment by paolorotolo** [comment]
Fixed in 1.3.0 and 1.3.0-foss.
