### ISSUE TITLE
Create Hacktoberfest label and add them to issues

### ISSUE THREAD

**Issue by danielgomezrico** [Glucosio/glucosio-android#312]
Hi guys,

Will be great if this project can be part of

https://hacktoberfest.digitalocean.com/

and to make it visible it should have Hacktoberfest label for issues

**Comment by emartynov** [comment]
Isn't it already: https://github.com/Glucosio/glucosio-android/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest

**Comment by emartynov** [comment]
Closing as not relevant. Please reopen if I'm wrong.
