### ISSUE TITLE
CSV Export doesn't work for Samsung S6

### ISSUE THREAD

**Issue by Ghazghkull** [Glucosio/glucosio-android#323]
Debugging your code into my computer and using my device the problem is located when the app tries to read the content from the Realm proxy:

```
                            GlucoseReading reading = readings.get(i);
                            osw.append(dateTool.convertRawDate(reading.getCreated() + ""));
```

The reading.getCreated() is always null

**Comment by Ghazghkull** [comment]
https://github.com/Glucosio/glucosio-android/pull/324

**Comment by emartynov** [comment]
Probably resolved!
