### ISSUE TITLE
Test Results: GlucoseRanges & InputFilter

### ISSUE THREAD

**Issue by bodziarr** [Glucosio/glucosio-android#358]
Hello. My group and I choose your app to test for our project in our Software Testing/Quality Assurance class at Miami University. Included in the document attached are the tests we performed: 
[FinalSubmission.pdf](https://github.com/Glucosio/glucosio-android/files/979584/FinalSubmission.pdf)
There was no option to create a test folder and include the tests, but those are included in this zip file as well:
[Test Files.zip](https://github.com/Glucosio/glucosio-android/files/979587/Test.Files.zip)

**Comment by emartynov** [comment]
Thanks a lot! I will shortly add them to the project :)

**Comment by bkerensa** [comment]
@emartynov are these ready to be added?

**Comment by ghost** [comment]
@emartynov , @bkerensa @paolorotolo I've already created MR with these test methods https://github.com/Glucosio/glucosio-android/pull/362.
