### ISSUE TITLE
Reboot the app could be delayed due to AlarmManager.set()

### ISSUE THREAD

**Issue by LiliWeiSE** [Glucosio/glucosio-android#369]
Hi, 

I found that AlarmManager.set() is used to reboot the app in [BackupActivity](https://github.com/Glucosio/glucosio-android/blob/2c93700e5d797734bcaf2b9d5d9a68cdb76d3d6b/app/src/main/java/org/glucosio/android/activity/BackupActivity.java#L303). For your information, after API 19, the alarm set by this API may not be delivered at the exact time and could be delayed.  [(Doc)](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))

Using setExact may avoid such delays.

**Comment by raacker** [comment]
Thanks for suggesting. It will be reviewed
