### ISSUE TITLE
Clean up gradle files

### ISSUE THREAD

**Issue by emartynov** [Glucosio/glucosio-android#388]
Proposal:

1. extract versions to ext properties
2. update dependencies to latest
3. fix all warning/suggestions from IDE

**Comment by AndyScherzinger** [comment]
In my opinion the way it should be handled. 👍

**Comment by ghost** [comment]
@emartynov this issue has `TODO` status in project. I think that this is already fixed. To check: https://github.com/Glucosio/glucosio-android/pull/411
