### ISSUE TITLE
Glucose Warnings on Input

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#56]
11.1 mmol/l (200 mg/dl) is hyperglycemia while symptoms may not show till 15–20 mmol/l (~250–300 mg/dl) we should warn the user in the input dialog when they enter a glucose level that enters this range and say something like "The value you have entered is within the hyperglycemia range, consider consulting a medical professional." but still record the value.

Below 3.9 mmol/L (70 mg/dL) is diagnostic for hypoglycemia so we should woarn "The value you have entered is near hypoglycemia" if its not yet below but if it is below we should warn "The value you have entered is within the hypoglycemia range, consider consulting a medical professional."

**Comment by bkerensa** [comment]
We will need some UI work on this for next release

**Comment by PaoloRotolo** [comment]
We can just show a Toast for Noce.

**Comment by bkerensa** [comment]
So lets not do this after all because if @satya164 fixes Issue #98 that would serve as a good guide and warnings would imho just be more nagging.

If everyone is ok with that we can close this?

**Comment by piotrek1543** [comment]
@PaoloRotolo I think Toast is a bit deprecated nowadays. I suggest you to use Snackbar.
