### ISSUE TITLE
Suggested blood glucose ranges

### ISSUE THREAD

**Issue by petercpg** [Glucosio/glucosio-android#91]
We should make a better description of blood glucose ranges suggested by different organizations. I know full titles are difficult to fit in UI design but I also believe abbreviation like ADA, AACE, UK Nice is not friendly to those who are not in US or UK. 

Also I'm not pretty sure if blood glucose ranges differs for people in different regions. For example TDA suggests to keep a 60-110mg/dl fasting glucose and < 140mg/dl glucose for 2 hours after meal, which looks quite different to what ADA and AACE suggests.

**Comment by bkerensa** [comment]
@satya164 Could we somehow fix this issue? Maybe a Info icon that opens a tool tip with brief description? Hmm 

@petercpg Could you provide a link to TDA?

**Comment by petercpg** [comment]
The numbers I mentioned above comes from Taiwan Diabetes Association at [1], their whole site is in Chinese. However I can find different suggestions from many local hospital/associations/doctors over the Internet, some just take ADA's suggestion while some takes from epidemiology researches. 

So maybe we could check if this standard range would be different for people from place to place, if not, we can simply use ADA+AACE+NICE+Custom, and ask users to consult their physician for their optimal ranges. Would this way better?

[1] http://homepage.vghtpe.gov.tw/~meta/hospital/teach1.htm

**Comment by riskysnail** [comment]
This is still an issue. I was going to open a new bug ticket but instead I'll comment on this one.

The acronyms are very cryptic. At the very least, the custom range boxes should be updated with the values of the selected preset (editing should remain disabled).

I like the tooltip idea to explain the acronyms.

**Comment by riskysnail** [comment]
I've got the custom range box fix ready to go. I'll see if I can get a tool tip to work.

It would be cool to auto-assign a range based on the country (kind of like a localization) but keeping a database up to date would be problematic. The guidelines between countries are very similar but the ranges still vary between treatment methods. See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3687090/

One option could be to do away with the presets and just have two choices - Recommended and Custom. Recommended could have some logic to change based on the users D-type. Just a suggestion, I don't have too much of an opinion one way or the other.
