### ISSUE TITLE
Color Guide

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#98]
***1 Upvote*** We should have a color guide somewhere maybe in assistant with labels explaining what colors mean

Red Dot (High)
Green Dot (Good)

etc etc

**Comment by bkerensa** [comment]
@satya164 @elioqoshi we will need some creative and design consult here

**Comment by bkerensa** [comment]
![screenshot_20151014-080229](https://cloud.githubusercontent.com/assets/859175/10487686/08263328-724a-11e5-9f6e-68b75f6887bf.png)

See in Diabetes:M how they have a color guide we need something like this but also need to find a appropriate place from the UX perspective for it to be.

**Comment by elioqoshi** [comment]
Cannot commit to this within this week. @satya164 can you take this over or should we find an alternative?

**Comment by satya164** [comment]
I won't be able to do it until end of next week.

**Comment by PaoloRotolo** [comment]
New colors are live in the app thanks to @rotolonico.

**Comment by PaoloRotolo** [comment]
Can we just add this in an Assistant's card?

**Comment by bkerensa** [comment]
But then it could be dismissed right? Ideally we want this right underneath the graph do we need Satya's guidance on this or could you perhaps do it? We just need the five colors above represented underneath graph with same text but  using this icon http://www.flaticon.com/free-icon/big-blood-drop_20762#term=blood-drop&page=1&position=1 (it could be made solid color without the white part) and also centered (Diabetes:M for some reason is left justified and that looks bad)

The force is strong with you! I think you got this

**Comment by bkerensa** [comment]
Oh and remember we will just to adjust the color in history etc since you do not use this many colors and I think currently use the same color for hypo and hyper!

**Comment by bkerensa** [comment]
@satya164 Are you able to work on this over the weekend?

**Comment by bkerensa** [comment]
@PaoloRotolo @satya164 is back can you provide the colors we currently use and which represents which so he can do mockup?

**Comment by PaoloRotolo** [comment]
Purple - Hypo;
Blue - Low;
Green - OK;
Yellow - High
Orange - Hyper;

**Comment by bkerensa** [comment]
@satya164 Need anything else here?

**Comment by satya164** [comment]
Nope, I'll give you the colors.

**Comment by satya164** [comment]
![colors](https://cloud.githubusercontent.com/assets/1174278/11019850/a023d4f4-8632-11e5-98c0-50547c1a4f5b.png)

Purple - #6F4EAB
Blue - #4B8DDB
Green - #749756
Yellow - #E7B85D
Orange - #E86445

**Comment by bkerensa** [comment]
@satya164 Would we put this right under the graph ideally and with the text label for each?

**Comment by bkerensa** [comment]
@PaoloRotolo This all you need?

**Comment by satya164** [comment]
@bkerensa Sounds good. Let's see how this looks in the app and if we need to tweak them @PaoloRotolo

**Comment by PaoloRotolo** [comment]
Okay, let's try. Thanks @satya164

**Comment by PaoloRotolo** [comment]
@satya164 
![screenshot_2015-11-08-12-21-55](https://cloud.githubusercontent.com/assets/5623301/11020050/5bd6ce24-8613-11e5-8b67-533a7a6824a0.png)

**Comment by bkerensa** [comment]
Is there any way we can do them horizontal?  That seems to take up a lot of space :) or can we put a vertical divider and put last check to the right of it?

**Comment by satya164** [comment]
Yeah, 2-3 columns will be fine. Also we should make the circles a little bigger to match the font height. And the font size can be a little smaller (12sp)?

**Comment by bkerensa** [comment]
@satya164 @PaoloRotolo on the graph do we want to also color each reading point?

**Comment by satya164** [comment]
Yeah, then wehave to tweak the graph though. Basically remove the pink lines and all, so the graph looks more neutral.

**Comment by PaoloRotolo** [comment]
I've used some iOS graphs as base.

![slack for ios upload](https://cloud.githubusercontent.com/assets/5623301/11020104/cf220dca-8614-11e5-933a-b66d7924208b.png)

**Comment by bkerensa** [comment]
@satya164 I see lets also get @elioqoshi's feedback on removing pink in graph and how that could impact the branding feel

**Comment by elioqoshi** [comment]
Would only the dots be colored? If it would be like the one @PaoloRotolo it would be a bit too colorful I'd say

**Comment by bkerensa** [comment]
@elioqoshi I believe if we are removing the pink like @satya164 proposed then just the dots would be colored. I really enjoy the pink though right now so idk what the best way forward is on this and defer to you and Satya on what would be most visibly appealing and functional.

**Comment by elioqoshi** [comment]
That should be okay then, would make sense.

**Comment by PaoloRotolo** [comment]
![screenshot_2015-11-08-12-41-56](https://cloud.githubusercontent.com/assets/5623301/11020138/22ad3b3a-8616-11e5-878c-a89f6fa2bd80.png)

**Comment by bkerensa** [comment]
I really like this much better @PaoloRotolo it makes better use of the space

**Comment by satya164** [comment]
Something like this? The legends can be scrollbale horizontally if they don't fit.

![3-glucosio-overview](https://cloud.githubusercontent.com/assets/1174278/11020187/97a3162c-863d-11e5-9f77-ab5bae63c51f.png)

**Comment by PaoloRotolo** [comment]
Okay

**Comment by bkerensa** [comment]
Looks nice :D maybe we can make the green a little greener? Like more of a holly or evergreen green? It looks like a mashed pea green right now :)

**Comment by satya164** [comment]
@bkerensa Will play with shades

**Comment by PaoloRotolo** [comment]
Did you mean this for graph?

![screenshot_2015-11-08-12-58-29](https://cloud.githubusercontent.com/assets/5623301/11020204/73f7e2ae-8618-11e5-831c-3d637859834f.png)

**Comment by satya164** [comment]
Without a dark pink line, the circles look weird if they have a void.

**Comment by bkerensa** [comment]
:+1:

**Comment by PaoloRotolo** [comment]
![screenshot_2015-11-08-13-02-22](https://cloud.githubusercontent.com/assets/5623301/11020222/177dfc10-8619-11e5-9014-65c7f7d3964a.png)

**Comment by satya164** [comment]
Yeah, better.

**Comment by PaoloRotolo** [comment]
BTW, I prefer the pink one, it looks confusing now.
What if we use pink lines and colored void circles?

**Comment by PaoloRotolo** [comment]
Ok, reduced circle size and looks better, yeah.

![screenshot_2015-11-08-16-07-03](https://cloud.githubusercontent.com/assets/5623301/11021003/8bbaef74-8633-11e5-970b-57952ce29382.png)

**Comment by PaoloRotolo** [comment]
Merging with issue #160: Clicking on graph legend would open a custom info dialog with values.
