### ISSUE TITLE
Add Language Selector

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#99]
***1 Upvote*** Users have indicated that using Android locale for language selection is not the best because Android doesn't support all languages we have already (Albanian for example). Also there are edge cases where someone might use UK english locale but prefer US English.

We should add the language selector to settings but still allow Android locale detection but the selector would override.

**Comment by birajkarmakar** [comment]
+1 for this idea.

**Comment by bkerensa** [comment]
Marking this as bitesize (see OpenHatch) this might be a good issue for Nico to work on.

**Comment by bkerensa** [comment]
@piotrek1543 @amouly would either of you like to take a go at this? :)

**Comment by amouly** [comment]
@bkerensa yeah! Personally I don't like the idea, because this cause some problems on Activity recreation and such. I have experience doing this before and a lot of issues came up. 

On the other hand, I really understand what you said about supporting edge cases. My case, for example, I'm using English-US for the Operative System, but I speak Spanish (I'm from Argentina). So I understand if there are users who wants to change the language just for this app.

If the intention is to include more people, I like the idea :smiley:

**Comment by bkerensa** [comment]
@amouly The main reason is because Android does not apparently support every language and so we have the apps translated to more languages that Android wont support. =/ 

The only way around this using the language switcher AFAIK but yes @PaoloRotolo ran into issues too when he tried implementing it.

**Comment by amouly** [comment]
@bkerensa yeah, it's hard because the Activity has a LOT of state, and can change for many reasons. But I understand your concern about languages, so we should try to do it. Do we have any idea where to locate the "language switch" or any code already done?

**Comment by piotrek1543** [comment]
@bkerensa @amouly well, it's not bad idea, but where do you want to put this feature: in app settings, or on the first run dialog (under "choose your location", would be choose your preffered language).

**Comment by birajkarmakar** [comment]
I think we can put it on the first run dialog as well as  in app settings because someone may want to choose different language after initial setup !

In Firefox for android, we have that feature.

**Comment by birajkarmakar** [comment]
also Android localization at runtime code sample is here http://programmerguru.com/android-tutorial/android-localization-at-runtime/ 

@bkerensa @amouly @piotrek1543 @PaoloRotolo please take a look.

**Comment by bkerensa** [comment]
Here is how Mozilla does their language picker http://mxr.mozilla.org/mozilla-central/source/mobile/android/base/preferences/LocaleListPreference.java

We could use it as a guide to make our own it also does checking for device fonts to make sure a device can display a specific language http://stackoverflow.com/questions/11815458/check-if-custom-font-can-display-character/22679283#22679283

**Comment by amouly** [comment]
@bkerensa we have some code commented on the Preferences activity for the Language chooser. Any thought why this is commented and which was the issue? 

@birajkarmakar The Mozilla example looks good, do they have a Git repository with that source code?

Thanks.

**Comment by bkerensa** [comment]
@PaoloRotolo Can you explain the issues we ran into?

@amouly http://mxr.mozilla.org/mozilla-central/source/mobile/android/base/preferences/LocaleListPreference.java

http://stackoverflow.com/questions/11815458/check-if-custom-font-can-display-character/22679283#22679283

This feature is important since Android does not support as many languages as we already have translated.

**Comment by PaoloRotolo** [comment]
@amouly Yes, all the code is commented. Basically idk why but it always forces locale to English. Even if my android language is italian. I've tried debugging it and I'm sure I set the right locale from the selector. It just reverts back to English. There's probably something that's changing the activity state and forcing locale to default again.

**Comment by amouly** [comment]
@PaoloRotolo did you test closing the Preferences activity (finish()) and restarting the app from the MainActivity? This way we force the system to use the new selected lang.

**Comment by PaoloRotolo** [comment]
Yes, I've also tried to read the preference on start in GlucosioApplication.java.
We already apply the custom font in GlucosioApplication just one time for all the app's activities.

**Comment by amouly** [comment]
@bkerensa so, based on the discussion with Ian Lake (on Google Plus) what we are going to do? I agree with Ian's comments, we should stick to Android Platform languages.

**Comment by elioqoshi** [comment]
I think it's unfair to say to stick with Android platform languages when it's not possible to bring on a language that way. If we are not inclusive we are only halfway open source, ideologically speaking.

**Comment by bkerensa** [comment]
@amouly The problem is Android Platform Languages are not consistent across devices depending on where device is sold and Android version. Ian said Albanian is supported on all modern versions of Android but @elioqoshi pointed out his phone does not have Albanian.

This is a problem because the OS has a locale fragmentation where if a device or region doesnt have the same locales that Android puports to support how can that user use Albanian or X language?

**Comment by emartynov** [comment]
Milestone is old. Are we really using them?

**Comment by emartynov** [comment]
Released with 1.1.0
